name: reactive_resume

services:
  postgres:
    image: ${POSTGRE_IMAGE:-postgres}:${POSTGRES_TAG:-latest}
    restart: ${RESTART_POLICY:-unless-stopped}
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "postgres"]
      start_period: 10s
      interval: 30s
      timeout: 10s
      retries: 3

  browserless:
    image: ghcr.io/browserless/chromium:latest
    restart: ${RESTART_POLICY:-unless-stopped}
    environment:
      - QUEUED=30
      - TIMEOUT=-1
      - HEALTH=true
      - CONCURRENT=20
      - TOKEN=1234567890
    healthcheck:
      test:
        ["CMD", "curl", "-f", "http://localhost:3000/pressure?token=1234567890"]
      interval: 10s
      timeout: 5s
      retries: 10

  # As an alternative to browserless, you can also use a lightweight image like chromedp/headless-shell:latest
  # See https://docs.rxresume.org/self-hosting/docker#alternative-printer-options for more information.
  # chrome:
  #   image: chromedp/headless-shell:latest
  #   restart: unless-stopped
  #   ports:
  #     - "9222:9222"

  seaweedfs:
    image: chrislusf/seaweedfs:latest
    restart: ${RESTART_POLICY:-unless-stopped}
    command: server -s3 -filer -dir=/data -ip=0.0.0.0
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-seaweedfs}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-seaweedfs}
    volumes:
      - seaweedfs_data:/data
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "/dev/null", "http://localhost:8888"]
      start_period: 10s
      interval: 30s
      timeout: 10s
      retries: 3

  seaweedfs-create-bucket:
    image: quay.io/minio/mc:latest
    restart: on-failure
    entrypoint: >
      /bin/sh -c "
        sleep 5;
        mc alias set seaweedfs http://seaweedfs:8333 seaweedfs seaweedfs;
        mc mb seaweedfs/reactive-resume;
        exit 0;
      "
    depends_on:
      seaweedfs:
        condition: service_healthy

  app:
    # image: pickit420/reactive-resume-v2:latest
    image: rrtest:latest
    # image: ghcr.io/pickit420/reactive-resume-v2:latest
    environment:
      # Server
      - TZ=${TZ:-Etc/UTC}
      - NODE_ENV=production
      - APP_URL=${APP_URL}
      - PRINTER_APP_URL=${PRINTER_APP_URL}
      # Printer
      - PRINTER_ENDPOINT=${PRINTER_ENDPOINT}
      # - PRINTER_ENDPOINT=ws://browserless:3000?token=1234567890
      # Database
      - DATABASE_URL=${DATABASE_URL}
      # - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/postgres
      # Authentication
      - AUTH_SECRET=${AUTH_SECRET}
      # - AUTH_SECRET=your_generated_auth_secret_here      
      # Storage
      - S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID:-seaweedfs}
      - S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY:-seaweedfs}
      - S3_ENDPOINT=${S3_ENDPOINT:-"http://seaweedfs:8333"}
      - S3_BUCKET=${S3_BUCKET:-reactive-resume}
      - S3_FORCE_PATH_STYLE=${S3_FORCE_PATH_STYLE:-true}
      # Google OAuth (optional)
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      # GitHub OAuth (optional)
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      # Custom OAuth (optional)
      - OAUTH_CLIENT_ID=${OAUTH_CLIENT_ID}
      - OAUTH_CLIENT_SECRET=${OAUTH_CLIENT_SECRET}
      - OAUTH_PROVIDER_NAME=${OAUTH_PROVIDER_NAME}
      - OAUTH_AUTHORIZATION_URL=${OAUTH_AUTHORIZATION_URL}
      - OAUTH_DISCOVERY_URL=${OAUTH_DISCOVERY_URL}
      # Email (optional)
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_SECURE=${SMTP_SECURE}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - SMTP_FROM=${SMTP_FROM}
      # Feature Flags
      - FLAG_DEBUG_PRINTER=${FLAG_DEBUG_PRINTER:-false}
      - FLAG_DISABLE_SIGNUPS=${FLAG_DISABLE_SIGNUPS:-false}
      - FLAG_DISABLE_EMAIL_AUTH=${FLAG_DISABLE_EMAIL_AUTH:-false}
      # Google Cloud Fonts (optional)
      - GOOGLE_CLOUD_API_KEY=${GOOGLE_CLOUD_API_KEY}
    volumes:
      - reactive_resume_data:/app/data
    ports:
      - "3001:3000"
    depends_on:
      postgres:
        condition: service_healthy
      browserless:
        condition: service_healthy
      seaweedfs-create-bucket:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      start_period: 10s
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
  seaweedfs_data:
  reactive_resume_data:
